service: pizonbe-user-management

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.secrets.APP_ENV_DEV}
  environment:
    DB_HOST: ${self:custom.secrets.DB_HOST}
    USER_DB: ${self:custom.secrets.USER_DB}
    USER_CRED_COLLECTION: ${self:custom.secrets.USER_CRED_COLLECTION}
    USER_ADDRESS_COLLECTION: ${self:custom.secrets.USER_ADDRESS_COLLECTION}
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}

functions:
  register:
    handler: functions/auth-manager.register
    events:
      - http:
          path: register
          method: post
          cors: true
  login:
    handler: functions/auth-manager.login
    events:
      - http:
          path: login
          method: post
          cors: true

  addAddress:
    handler: functions/address-manager.addAddress
    events:
      - http:
          path: addAddress
          method: post
          cors: true
  getAddress:
    handler: functions/address-manager.getAddress
    events:
      - http:
          path: getAddress/{addId}
          method: get
          cors: true
      - http:
          path: getAddress
          method: get
          cors: true
